<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

 <xacro:include filename="$(find car_description)/urdf/materials.xacro"/>

  <xacro:property name="base_length" value="0.1"/>
    <xacro:property name="base_width" value="0.1"/>
    <xacro:property name="base_height" value="0.01"/>
    <xacro:property name="base_mass" value="0.005"/>
    <xacro:property name="piller2_length" value="0.03"/>
    <xacro:property name="piller2_radius" value="0.02"/>

<!-- =================== Kinect ==================== -->
  <link name="camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 ${pi/2}"/>
      <geometry>
        <mesh filename="package://car_description/meshes/sensors/kinect.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.28 0.07 0.08"/>
      </geometry>
    </collision>
    <!-- <xacro:default_inertial mass="0.2"/> -->
  </link>
  
  <joint name="kinect_base_joint" type="fixed">
    <origin xyz="0 0 ${base_height*4}" rpy="0 0 0"/>
    <parent link="kinect_base"/>
    <child link="camera_link"/>
  </joint>

       <link name="kinect_base">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${base_mass}" x="0" y="0" z="0">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    
    <gazebo reference="kinect_base">
        <material>Gazebo/black</material>
    </gazebo>

    <joint name="piller2_base_joint" type="fixed">
        <parent link="piller2_link"/>
        <child link="kinect_base"/>
        <origin xyz="0 0 ${piller2_length/2}" rpy="0 0 0"/>
    </joint>

<link name="piller2_link">
    <visual>
        <geometry>
            <cylinder length="${piller2_length}" radius="${piller2_radius}"/>
        </geometry>
        <material name="blue"/>
    </visual>
    <collision>
        <origin xyz="0 0 0"/>
        <geometry>
            <cylinder length="${piller2_length}" radius="${piller2_radius}"/>
        </geometry>
    </collision>
  </link>

    <joint name="piller2_chassis_joint" type="fixed">
        <parent link="chassis"/>
        <child link="piller2_link"/>
        <origin xyz="0.1 0 0.04" rpy="0 0 0"/>
    </joint>
  
  <joint name="kinect_depth_joint" type="fixed">
    <origin xyz="0 0.011 0" rpy="0 0 0" />
    <parent link="camera_link" />
    <child link="camera_depth_frame" />
  </joint>

  <link name="camera_depth_frame">
    <inertial>
      <mass value="0.01" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
        iyy="0.001" iyz="0.0"
        izz="0.001" />
    </inertial>
  </link>

  <joint name="camera_depth_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
    <parent link="camera_depth_frame" />
    <child link="camera_depth_optical_frame" />
  </joint>

  <link name="camera_depth_optical_frame">
    <inertial>
      <mass value="0.001" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
        iyy="0.0001" iyz="0.0"
        izz="0.0001" />
    </inertial>
  </link>

  <joint name="camera_rgb_joint" type="fixed">
    <origin xyz="0 -0.012 0" rpy="0 0 0" />
    <parent link="camera_link" />
    <child link="camera_rgb_frame" />
  </joint>

  <link name="camera_rgb_frame">
    <inertial>
      <mass value="0.001" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
        iyy="0.0001" iyz="0.0"
        izz="0.0001" />
    </inertial>
  </link>

  <joint name="camera_rgb_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
    <parent link="camera_rgb_frame" />
    <child link="camera_rgb_optical_frame" />
  </joint>

  <link name="camera_rgb_optical_frame">
    <inertial>
      <mass value="0.001" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
        iyy="0.0001" iyz="0.0"
        izz="0.0001" />
    </inertial>
  </link>

</robot>
